export const SELECT_CATEGORY = "SELECT_CATEGORY"
// ====== POSTS ======
export const SELECT_POST = "SELECT_POST"
export const VOTE_POST = "VOTE_POST"
export const DELETE_POST = "DELETE_POST"
export const SUBMIT_POST = "SUBMIT_POST"
export const SORT_POSTS = "SORT_POSTS"
export const GET_POST_TO_EDIT = "GET_POST_TO_EDIT"
export const SUBMIT_EDITED_POST = "SUBMIT_EDITED_POST"
export const CANCEL_EDIT_POST = "CANCEL_EDIT_POST"
// ====== COMMENTS ======
export const GET_SELECTED_POST_COMMENTS = "GET_SELECTED_POST_COMMENTS"
export const SUBMIT_COMMENT = "SUBMIT_COMMENT"
export const VOTE_COMMENT = "VOTE_COMMENT"
export const GET_COMMENT_TO_EDIT = "GET_COMMENT_TO_EDIT"
export const SUBMIT_EDITED_COMMENT = "SUBMIT_EDITED_COMMENT"
export const CANCEL_EDIT_COMMENT = "CANCEL_EDIT_COMMENT"
export const DELETE_COMMENT = "DELETE_COMMENT"
// ====== MODAL ======
export const OPEN_LOGIN_MODAL = "OPEN_LOGIN_MODAL"
export const CLOSE_LOGIN_MODAL = "CLOSE_LOGIN_MODAL"
export const SET_USER_LOGIN = "SET_USER_LOGIN"
// ====== SEARCH ======
export const SET_SEARCH_KEY_WORD = "SET_SEARCH_KEY_WORD"
